### PR TITLE
WIP: Expand subscription interface

### PR DESCRIPTION
**Pull request by crozzy**
It is currently hard to use the Subscription interface to implement your own Subscription instance, this makes it hard to mock in a unit test situation.

### CODE REVIEW

**Comment by kozlovic** [comment]
@crozzy Sorry for not getting back earlier to you. I don't think that this is something we would merge. I don't like that we would make RLock(), etc.. part of the interface. This looks really strange.

Ack() should have been part of the Subscription. It was put under Msg because easier access in the callback and looking better than doing `msg.Sub.Ack(msg)`. We could of course have passed the subscription in the message handler for direct access.

If you implement your own Subscription, you would still need to acknowledge the message, which means sending an `Ack` protobuf to the ack subject to the server. 

Maybe you could use a function to ack your message and check if msg.Sub is of the type of your Subscription, if then, do your own acking.

**Comment by crozzy** [comment]
@kozlovic thanks for the reply, I agree having a non-native method as part of the Subscription interface looks strange (although it does seems like read-locking is an essential part of both implementations). I also think the syntax gains between `msg.Sub.Ack(msg)` and `msg.Ack()` makes sense.

I guess my point is how can you unit-test a `MsgHandler` function that `Ack`s the message (without spinning up a NATS server). 

I think I will go down the more integration test route for now. Thanks again

**Comment by kozlovic** [comment]
At this point, what I would do if I were you is create a helper API to acknowledge a message, say:
```
func ack(msg *stan.Msg) {
    if _, mockSub := msg.Sub.(*myMockSub); mockSub {
        // skip ack
    } else {
        msg.Ack()
    }
}
```
assuming your subscription implementation is called `myMockSub`, and use `ack(msg)` in your code in place where you would call `msg.Ack()`.

Does that sound reasonable?

**Comment by crozzy** [comment]
Yes, sounds reasonable. Having mock code in production is difficult to swallow for me.

If `Msg` was an interface, this could be `func (m *myMsgImpl) Ack()` but that is a whole can of worms with the embedded `MsgProto`.

Thanks for the info @kozlovic

**Pull request closed without merging**
