### PR TITLE
[ci skip] Updates to Readme.md

### PR DESCRIPTION
**Pull request by aricart**
[REMOVED] Removed limitations that have been addressed in subsequent versions of the server or api.

[ADDED] Note describing that streaming server subscriptions do not support wildcards.

@kozlovic @ColinSullivan1 @lparis

### CODE REVIEW

**Comment by kozlovic** [comment]
I would put the limitation in bold or something to make it more obvious.

**Comment by kozlovic** [comment]
Or even, after chapter `Installation` and before `Basic Usage`, a chapter `Wildcards` that says that they are not supported. Users would look for a description on how to use Wildcards and be informed that they are not supported.

**Comment by aricart** [comment]
Good idea. Put the note under the "Wildcard Subscriptions" header. As this makes it obvious.

@kozlovic @ColinSullivan1

**Comment by kozlovic** [comment]
LGTM

**Comment by ColinSullivan1** [comment]
LGTM.

**Pull request merged**
